### ISSUE TITLE
Web3Modal Integration for Wallet Display

### ISSUE THREAD

**Issue by farunurisonmez** [efsoftworks/nft-marketplace-app#22]
This task aims to implement the display of Ethereum wallets using the Web3Modal library. The integration includes opening a connection modal that allows users to link their wallets and choose networks.

1. Web3Modal Configuration:

Configure Web3Modal in your project using the createWeb3Modal function.
Define Ethereum networks (as seen in the example with mainnet).
Specify project-specific metadata information.

2. Create Web3Modal Provider:

Create the Web3ModalProvider component and integrate it into your project structure.

3. Display Wallet:

Manage wallet connection using the useWeb3Modal hook.
Create a component that opens the wallet connection modal when a button is clicked.

Notes:
This integration provides an interactive experience, allowing users to link their wallets and choose networks.
Web3Modal may be compatible with other popular networks besides Ethereum.
The connection modal can be enriched with user-friendly and customizable text and icons.
After completing this task, your users will have an interactive tool to link their wallets and choose networks.

**Comment by 0xfaru** [comment]
Implement wallet display integration in the Navbar component.
